'use strict';
const {XMLParser,XMLValidator}=require('fast-xml-parser');
const array=x=>x==null?[]:Array.isArray(x)?x:[x];
function weight(p){
 for(const k of ['weight_in_pounds','package_weight_in_pounds'])if(p[k]!=null&&p[k]!==''&&Number.isFinite(Number(p[k])))return Number(p[k]);
 const w=p.weight;if(w&&typeof w==='object'){const n=Number(w.value),u=String(w.units||w.unit||'').toLowerCase();if(Number.isFinite(n)){if(['lb','lbs','pounds','pound'].includes(u))return n;if(['kg','kilograms','kilogram'].includes(u))return n*2.2046226218;if(['oz','ounces','ounce'].includes(u))return n/16;}}
 return null;
}
function listingId(p){for(const k of ['marketplace_id','ebay_item_id','marketplace_item_id','external_listing_id','listing_id','item_id'])if(/^\d{9,15}$/.test(String(p[k]||'')))return String(p[k]);for(const u of [p.listing_url,p.marketplace_url,p.ebay_url]){const m=String(u||'').match(/ebay\.[^/]+\/itm\/(?:[^/]+\/)?(\d{9,15})/i);if(m)return m[1]}return ''}
function picture(p){for(const v of [p.primary_image_url,p.image_url,p.primary_image,...array(p.images),...array(p.product_images)]){const s=typeof v==='string'?v:v?.large_image_url||v?.original_image_url||v?.url||v?.image_url;if(/^https?:\/\//i.test(s||''))return s}return ''}
function classify(xml){if(XMLValidator.validate(xml)!==true)throw Error('eBay returned invalid XML.');const data=new XMLParser({ignoreAttributes:false,removeNSPrefix:true,parseTagValue:false}).parse(xml).GetItemResponse;if(!data||!['Success','Warning'].includes(data.Ack))throw Error(array(data?.Errors).map(e=>e.LongMessage||e.ShortMessage).join('; ')||'eBay did not return a successful GetItem response.');const item=data.Item;if(!item)throw Error('eBay returned no listing.');const active=item.SellingStatus?.ListingStatus==='Active',shipping=item.ShippingDetails||{},type=shipping.ShippingType||'',services=array(shipping.ShippingServiceOptions).map(s=>({service:s.ShippingService||'',free:['true','1'].includes(String(s.FreeShipping).toLowerCase()),cost:s.ShippingServiceCost?.['#text']??s.ShippingServiceCost}));const free=type==='Free'||services.some(s=>s.free||(type!=='FreightFlat'&&s.cost!==undefined&&s.cost!==''&&Number(s.cost)===0));return {active,item_id:String(item.ItemID||''),ebay_sku:String(item.SKU||''),status:!item.SellingStatus?.ListingStatus?'unknown':!active?'ended':type==='FreightFlat'&&!free?'freight':!type?'unknown':free?'free':'not-freight',shipping_type:type,services,title:item.Title||'',listing_status:item.SellingStatus?.ListingStatus||'Unknown'};}
module.exports={weight,listingId,picture,classify};
