'use strict';
const express=require('express'),fs=require('fs'),path=require('path');
const {weight,listingId,picture,classify}=require('./audit');
const app=express(),dir=path.resolve(process.env.DATA_DIR||'data'),file=path.join(dir,'freight-audit.json');fs.mkdirSync(dir,{recursive:true});
let state={rows:[],job:{running:false,phase:'Not scanned yet',products:0,checked:0,errors:[]},updated_at:null};
if(fs.existsSync(file))state=JSON.parse(fs.readFileSync(file,'utf8'));if(state.job.running){state.job.running=false;state.job.phase='Interrupted by server restart. Saved results retained; start a new audit.';}
const deletionBlock=path.join(dir,'ebay-deletion-block.json');
const blocked=()=>fs.existsSync(deletionBlock);
const save=()=>{if(blocked()){state.rows=[];state.job.running=false;state.job.phase='eBay data cleared following account deletion notification. eBay audit paused.';}fs.writeFileSync(file+'.tmp',JSON.stringify(state));fs.renameSync(file+'.tmp',file)};
const configured=()=>!blocked()&&Boolean(process.env.EBAY_USER_ACCESS_TOKEN||(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET&&process.env.EBAY_REFRESH_TOKEN));
const refreshConfigured=()=>Boolean(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET&&process.env.EBAY_REFRESH_TOKEN);
let auth={token:'',expires:0},cancel=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function token(){if(refreshConfigured()){if(auth.expires>Date.now()+60000)return auth.token;const r=await fetch('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(process.env.EBAY_CLIENT_ID+':'+process.env.EBAY_CLIENT_SECRET).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:process.env.EBAY_REFRESH_TOKEN}),signal:AbortSignal.timeout(30000)});const b=await r.json();if(!r.ok||!b.access_token)throw Error('eBay authorization failed. Check the Render eBay credentials and seller consent.');auth={token:b.access_token,expires:Date.now()+Number(b.expires_in)*1000};return auth.token}return process.env.EBAY_USER_ACCESS_TOKEN;}
async function ebay(id){if(blocked())throw Error('eBay audit paused after account deletion notification.');if(!configured())throw Error('eBay credentials needed. See setup instructions.');for(let attempt=0;attempt<3;attempt++){await sleep(1000);const r=await fetch('https://api.ebay.com/ws/api.dll',{method:'POST',headers:{'Content-Type':'text/xml','X-EBAY-API-CALL-NAME':'GetItem','X-EBAY-API-SITEID':process.env.EBAY_SITE_ID||'0','X-EBAY-API-COMPATIBILITY-LEVEL':'1477','X-EBAY-API-IAF-TOKEN':await token()},body:`<?xml version="1.0" encoding="utf-8"?><GetItemRequest xmlns="urn:ebay:apis:eBLBaseComponents"><ItemID>${id}</ItemID><DetailLevel>ReturnAll</DetailLevel></GetItemRequest>`,signal:AbortSignal.timeout(30000)});if(r.status===429){state.job.phase='Waiting for eBay rate limit';save();await sleep(Math.max(60000,Number(r.headers.get('retry-after')||0)*1000));continue}if(!r.ok)throw Error('eBay HTTP '+r.status);return classify(await r.text())}throw Error('eBay rate limit persists.');}
async function sc(endpoint){const r=await fetch((process.env.TAG_SORT_INTERNAL_URL||'http://127.0.0.1:3106')+'/internal/freight-read?path='+encodeURIComponent(endpoint),{headers:{'x-suite-internal-key':process.env.SUITE_INTERNAL_KEY||''},signal:AbortSignal.timeout(480000)});const b=await r.json();if(!r.ok)throw Error(b.error||'SellerChamp read failed');return b;}
function row(p){return {key:String(p.id),product_id:p.id,sku:p.sku||p.custom_catalogue_sku||'',title:p.title||p.product_title||'',weight_lb:weight(p),image:picture(p),location:(p.inventory_locations||[]).map(x=>x.location).filter(Boolean).join(', ')||p.bin_location||p.location||p.locations||'',listing_id:listingId(p),sellerchamp_shipping:p.ebay_shipping_policy_name||p.shipping_charge_type||p.shipping_type||p.shipping_service||p.shipping_profile_name||'Not supplied by SellerChamp API',status:'unknown',message:'Not checked',checked_at:null}}
async function check(r){try{if(!r.listing_id)throw Error('eBay listing ID missing. Enter the listing ID to check it.');const b=await ebay(r.listing_id);if(b.item_id!==r.listing_id)throw Error('eBay returned a different listing ID. Review the match.');if(b.ebay_sku&&r.sku&&b.ebay_sku.toLowerCase()!==String(r.sku).toLowerCase())throw Error('eBay SKU differs from SellerChamp. Review the listing match.');Object.assign(r,b,{message:b.status==='freight'?'Negotiated freight confirmed':b.status==='ended'?'eBay listing is not active':b.status==='free'?'Free shipping detected':b.status==='unknown'?'Shipping type missing':'Negotiated freight is not configured',checked_at:new Date().toISOString()});}catch(e){r.status='unknown';r.message=e.message;r.checked_at=new Date().toISOString()}state.job.checked++;save();}
async function scan(){cancel=false;state.job={running:true,phase:'Reading SellerChamp products',products:0,checked:0,errors:[]};save();const rows=[];const seen=new Set();try{const accounts=await sc('/api/marketplace_accounts');if(!Array.isArray(accounts.marketplace_accounts))throw Error('SellerChamp marketplace accounts are missing.');const ebayAccounts=new Set(accounts.marketplace_accounts.filter(a=>String(a.marketplace||a.marketplace_account_type||'').toLowerCase().includes('ebay')).map(a=>String(a.id)));if(!ebayAccounts.size)throw Error('No eBay marketplace account connected in SellerChamp.');for(let page=1;page<=1000;page++){if(cancel)break;state.job.phase='Reading SellerChamp page '+page;save();const b=await sc('/api/products?page='+page+'&page_size=100');if(!Array.isArray(b.products))throw Error('SellerChamp did not supply a products array.');for(const p of b.products){state.job.products++;if(p.marketplace_account_id&&!ebayAccounts.has(String(p.marketplace_account_id)))continue;const w=weight(p);if(w===null){state.job.missing_weight=(state.job.missing_weight||0)+1;continue}if(w<=80)continue;const channel=String(p.marketplace_name||p.marketplace||p.channel||'').toLowerCase();if(channel&&['amazon','etsy','walmart','shopify'].some(x=>channel.includes(x)))continue;const status=String(p.list_status||p.marketplace_status||p.status||'').toLowerCase();if(['inactive','ended','deleted','not_submitted','draft'].includes(status))continue;if(!p.id){state.job.errors.push('Heavy product missing SellerChamp ID skipped.');continue}const r=row(p);if(seen.has(r.key))continue;seen.add(r.key);try{const detail=await sc('/api/products/'+encodeURIComponent(p.id)+'.json');const full=detail.product||detail;const fresh=row({...p,...full});if(fresh.weight_lb!==null&&fresh.weight_lb<=80)continue;Object.assign(r,fresh)}catch(e){state.job.errors.push('Product '+r.sku+' detail: '+e.message)}rows.push(r);}state.rows=rows;save();if(b.products.length<100)break;if(page===1000)throw Error('Catalog page limit reached. Audit is incomplete.');}if(!cancel&&configured()){state.job.phase='Checking live eBay listings';for(const r of rows){if(cancel)break;await check(r)}}state.job.phase=cancel?'Stopped; partial results saved':configured()?'Finished':'SellerChamp scan finished. Configure eBay credentials to verify listings.';state.updated_at=new Date().toISOString();}catch(e){state.job.errors.push(e.message);state.job.phase='Incomplete: '+e.message;}finally{state.job.running=false;save()}}
app.use(express.json({limit:'10kb'}));
app.post('/internal/account-deletion',(q,r)=>{if(!process.env.SUITE_INTERNAL_KEY||q.headers['x-suite-internal-key']!==process.env.SUITE_INTERNAL_KEY)return r.sendStatus(403);cancel=true;fs.writeFileSync(deletionBlock,JSON.stringify({blocked_at:new Date().toISOString()}));state.rows=[];state.job={running:false,phase:'eBay audit paused following account deletion notification.',products:0,checked:0,errors:[]};auth={token:'',expires:0};save();r.sendStatus(204)});app.use(express.static(path.join(__dirname,'public')));
app.get('/api/status',(q,r)=>r.json({...state,ebay_configured:configured()}));
app.post('/api/scan',(q,r)=>{if(blocked())return r.status(409).json({error:'eBay audit paused after account deletion notification.'});if(state.job.running)return r.status(409).json({error:'An audit is already running.'});r.json({ok:true});void scan()});
app.post('/api/stop',(q,r)=>{cancel=true;r.json({ok:true})});
app.post('/api/recheck/:id',async(q,r)=>{if(state.job.running)return r.status(409).json({error:'Wait for the running audit to finish.'});const x=state.rows.find(x=>x.key===q.params.id);if(!x)return r.status(404).json({error:'Item not found.'});if(q.body.listing_id){if(!/^\d{9,15}$/.test(String(q.body.listing_id)))return r.status(400).json({error:'Enter a numeric eBay listing ID (9–15 digits).'});x.listing_id=String(q.body.listing_id)}state.job.running=true;try{await check(x);r.json({ok:true,row:x})}finally{state.job.running=false;save()}});
app.listen(process.env.PORT||3109,'0.0.0.0',()=>console.log('Freight Shipping Audit ready'));
