'use strict';
const FIELDS=['sale','buyer_shipping','selling_fees','advertising_fees','shipping_cost','refund'];
function cents(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);if(!Number.isFinite(n)||n<0||n>10000000)throw Error('Amounts must be between 0 and 10,000,000.');return Math.round(n*100)}
function totals(row){const missing=FIELDS.filter(k=>row.amounts[k]===null||row.amounts[k]===undefined);const a=row.amounts;const net=missing.length?null:a.sale+a.buyer_shipping-a.selling_fees-a.advertising_fees-a.shipping_cost-a.refund;const share=net===null?null:Math.round(net/2);const paid=(row.payments||[]).reduce((n,p)=>n+p.amount,0);return {missing,net,share,paid,balance:share===null?null:share-paid,ready:!missing.length&&row.reviewed===true&&row.currency==='USD'};}
function tags(p){const values=p?.tags_array??p?.tags??p?.tag_list??p?.product_tags??[];return (Array.isArray(values)?values:String(values).split(',')).map(t=>String(typeof t==='string'?t:t?.name||t?.tag||'').trim());}
function hasGlen(p){return tags(p).some(t=>t.toLowerCase()==='glen')}
function optional(v){return v===null||v===undefined||v===''?null:cents(v)}
function fromOrder(order,item,product,key){const qty=Number(item.quantity);const sale=Number.isFinite(qty)&&qty>0&&item.unit_price!==undefined&&item.unit_price!==null?cents(Number(item.unit_price)*qty):null;const one=order.items.length===1;return {id:key,consigner:'Glen',order_number:String(order.order_number||''),order_id:String(order.id||order.order_id||''),order_item_id:String(item.order_item_id||item.id||''),sku:String(item.variant_sku||item.sku||''),product_id:String(product?.id||item.product_id||''),title:String(item.title||product?.title||''),quantity:qty,date:order.purchased_at||order.order_date||order.created_at||'',currency:String(item.currency_code||order.currency_code||'UNKNOWN').toUpperCase(),status:String(order.order_status||'unknown'),amounts:{sale,buyer_shipping:optional(item.shipping_amount??(one?order.total_shipping:undefined)),selling_fees:optional(item.marketplace_fees),advertising_fees:null,shipping_cost:null,refund:null},shipping_kind:'estimate',reviewed:false,notes:'',weight:product?.package_weight_in_pounds!=null?`${product.package_weight_in_pounds} lb (package)`:product?.weight_in_pounds!=null?`${product.weight_in_pounds} lb (item)`:item.weight?`${item.weight.value} ${item.weight.units||''}`:'Not supplied',dimensions:product?.package_dimensions||product?.item_dimensions||null,payments:[],history:[],manual_fields:[],source_checked_at:new Date().toISOString()};}
module.exports={FIELDS,cents,totals,hasGlen,fromOrder};
