'use strict';
const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {FIELDS,cents,totals,hasGlen,fromOrder}=require('./ledger');
const app=express(),DIR=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data')),FILE=path.join(DIR,'consignment.json');
fs.mkdirSync(DIR,{recursive:true});
function read(){if(!fs.existsSync(FILE))return {rows:[]};const db=JSON.parse(fs.readFileSync(FILE,'utf8'));if(!Array.isArray(db.rows))throw Error('Ledger file is invalid. Restore a backup before continuing.');return db}
function write(db){fs.writeFileSync(FILE+'.tmp',JSON.stringify(db,null,2));fs.renameSync(FILE+'.tmp',FILE)}
function history(row,action,details){row.history.push({at:new Date().toISOString(),action,details});row.updated_at=new Date().toISOString()}
let stopRequested=false;
let job={running:false,phase:'idle',orders:0,items:0,matched:0,added:0,errors:[],waiting_seconds:0},queue=Promise.resolve(),last=0;
const BASE=(process.env.SELLERCHAMP_BASE_URL||'https://app.sellerchamp.com').replace(/\/$/,''),TOKEN=process.env.SELLERCHAMP_TOKEN||process.env.SELLERCHAMP_API_TOKEN||'';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function sc(endpoint){const task=queue.then(async()=>{if(!TOKEN)throw Error('SellerChamp token is not configured.');for(let i=0;i<4;i++){await sleep(Math.max(0,Number(process.env.CONSIGNMENT_REQUEST_GAP_MS||3000)-(Date.now()-last)));last=Date.now();const r=await fetch(BASE+endpoint,{headers:{Token:TOKEN,Accept:'application/json'},signal:AbortSignal.timeout(30000)});if(r.status===429){const delay=Math.max(60000,Number(r.headers.get('retry-after')||0)*1000);job.waiting_seconds=Math.ceil(delay/1000);await sleep(delay);continue}job.waiting_seconds=0;const body=await r.json();if(!r.ok)throw Error(`SellerChamp ${r.status}: ${body.error||body.message||'Request failed'}`);return body}throw Error('SellerChamp rate limit persists. Try again later.')});queue=task.catch(()=>{});return task}
async function productFor(order,item,cache){const sku=String(item.variant_sku||item.sku||''),key=`${order.marketplace_account_id||''}|${item.product_id||''}|${sku}`;if(cache.has(key))return cache.get(key);let p;if(item.product_id){try{const b=await sc('/api/products/'+encodeURIComponent(item.product_id));p=b.product}catch(e){if(!e.message.includes('404'))throw e}}if(!p&&sku){const b=await sc(`/api/products?sku=${encodeURIComponent(sku)}&marketplace_account_id=${encodeURIComponent(order.marketplace_account_id||'')}&page_size=100`);const matches=(b.products||[]).filter(p=>String(p.sku)===sku||(p.variants||[]).some(v=>String(v.sku)===sku));if(matches.length>1&&matches.some(hasGlen)&&matches.some(p=>!hasGlen(p)))throw Error('Ambiguous product match for SKU '+sku);p=matches.find(hasGlen)||matches[0]}if(!p)throw Error('No exact product match for '+sku);cache.set(key,p);return p}
async function scan(start,end,orderNumber){stopRequested=false;job={running:true,phase:'Reading orders',orders:0,items:0,matched:0,added:0,errors:[],waiting_seconds:0};const cache=new Map();try{for(let page=1;page<=200;page++){if(stopRequested)throw Error('Scan stopped by you. Imported entries are saved.');const params=new URLSearchParams({page:String(page),page_size:'100',sort:'purchased_at',direction:'DESC'});if(orderNumber)params.set('order_number',orderNumber);else{params.set('purchased_at_start',start);params.set('purchased_at_end',end+'T23:59:59')}const body=await sc('/api/orders?'+params),orders=body.orders||[];for(const order of orders){if(stopRequested)throw Error('Scan stopped by you. Imported entries are saved.');if(orderNumber&&String(order.order_number)!==orderNumber)continue;job.orders++;job.phase='Checking product tags';const items=order.items||[];for(let index=0;index<items.length;index++){const item=items[index];job.items++;const orderKey=String(order.id||order.order_id||order.order_number||'');if(!orderKey){job.errors.push('Order without an identifier skipped.');continue}const line=String(item.order_item_id||item.id||`${item.variant_sku||item.sku||''}|${index}`),key=JSON.stringify([String(order.marketplace_account_id||''),orderKey,line]);try{const existing=read().rows.find(r=>r.id===key);if(order.paid!==true&&!existing)continue;let product=await productFor(order,item,cache);if(!existing&&!hasGlen(product))continue;job.matched++;const imported=fromOrder({...order,items},item,product,key);const db=read(),row=db.rows.find(r=>r.id===key);if(!row){history(imported,'imported','Matched Glen product tag. Review amounts and refunds before payment.');db.rows.push(imported);job.added++}else{let changed=row.status!==imported.status||row.currency!==imported.currency||row.quantity!==imported.quantity||order.paid!==true;row.status=imported.status;row.currency=imported.currency;row.quantity=imported.quantity;row.weight=imported.weight;row.dimensions=imported.dimensions;row.source_checked_at=imported.source_checked_at;for(const field of ['sale','buyer_shipping','selling_fees']){if(!(row.manual_fields||[]).includes(field)&&row.amounts[field]!==imported.amounts[field]){row.amounts[field]=imported.amounts[field];changed=true}}if(changed){row.reviewed=false;history(row,'source_changed','Order amounts or status changed; review again.')}}write(db)}catch(e){job.errors.push(`Order ${order.order_number||orderKey}, SKU ${item.sku||''}: ${e.message}`)}}}if(orders.length<100)break;if(page===200)throw Error('Scan reached 200 pages. Use a shorter date range.')}job.phase=job.errors.length?'Finished with items needing attention':'Finished';}catch(e){job.errors.push(e.message);job.phase='Stopped'}finally{job.running=false;job.finished_at=new Date().toISOString()}}
app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/status',(q,r)=>r.json({configured:!!TOKEN,job,version:'1.0.0'}));
app.post('/api/check-connection',async(q,r)=>{try{await sc('/api/marketplace_accounts');r.json({ok:true})}catch(e){r.status(502).json({error:e.message})}});
app.get('/api/ledger',(q,r)=>{try{r.json({rows:read().rows.map(row=>({...row,totals:totals(row)})),job})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/stop',(q,r)=>{stopRequested=true;r.json({ok:true})});
app.post('/api/sync',(q,r)=>{if(job.running)return r.status(409).json({error:'A scan is already running.'});const {start,end,order_number}=q.body||{};const number=String(order_number||'').trim();if(!number){if(!/^\d{4}-\d{2}-\d{2}$/.test(start||'')||!/^\d{4}-\d{2}-\d{2}$/.test(end||'')||!Number.isFinite(Date.parse(start))||!Number.isFinite(Date.parse(end))||Date.parse(end)<Date.parse(start)||Date.parse(end)-Date.parse(start)>366*86400000)return r.status(400).json({error:'Choose a valid date range of up to one year.'})}scan(start,end,number);r.status(202).json({ok:true})});
app.post('/api/entry/:id', (q,r)=>{try{const db=read(),row=db.rows.find(x=>x.id===q.params.id);if(!row)return r.status(404).json({error:'Entry not found.'});for(const field of FIELDS){if(Object.hasOwn(q.body.amounts||{},field)){const value=cents(q.body.amounts[field]);if(value!==row.amounts[field]){row.amounts[field]=value;row.manual_fields=[...new Set([...(row.manual_fields||[]),field])]}}}row.notes=String(q.body.notes||'').slice(0,4000);row.shipping_kind=q.body.shipping_kind==='actual'?'actual':'estimate';row.reviewed=q.body.reviewed===true;history(row,'edited','Reviewed amounts saved.');write(db);r.json({ok:true,row:{...row,totals:totals(row)}})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/entry/:id/payment',(q,r)=>{try{const db=read(),row=db.rows.find(x=>x.id===q.params.id);if(!row)return r.status(404).json({error:'Entry not found.'});const t=totals(row);if(!t.ready||t.balance===0)return r.status(400).json({error:'Review every amount and currency before recording payment.'});if(q.body.expected_balance!==t.balance)return r.status(409).json({error:'Balance changed. Reload and review it before recording payment.'});const reference=String(q.body.reference||'').trim();if(!reference)return r.status(400).json({error:'Enter a payment reference or note.'});row.payments.push({id:crypto.randomUUID(),at:new Date().toISOString(),amount:t.balance,reference,shipping_kind:row.shipping_kind,amounts:{...row.amounts}});history(row,'payment_recorded',reference);write(db);r.json({ok:true,row:{...row,totals:totals(row)}})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/backup',(q,r)=>{try{r.attachment('consignment-ledger-backup.json').json(read())}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/export',(q,r)=>{try{const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const fields=['Consigner','Order','SKU','Title','Currency','Sale','Buyer shipping','Selling fees','Advertising fees','Shipping cost','Refund','Glen share','Recorded paid','Balance','Reviewed','Shipping type'];const rows=read().rows.map(x=>{const t=totals(x);return [x.consigner,x.order_number,x.sku,x.title,x.currency,...FIELDS.map(k=>x.amounts[k]==null?'':(x.amounts[k]/100).toFixed(2)),t.share==null?'':(t.share/100).toFixed(2),(t.paid/100).toFixed(2),t.balance==null?'':(t.balance/100).toFixed(2),x.reviewed,x.shipping_kind].map(v=>quote(typeof v==='string'&&/^[=+@\-]/.test(v)?"'"+v:v)).join(',')});r.attachment('Glen-consignment.csv').type('text/csv').send([fields.map(quote).join(','),...rows].join('\r\n'))}catch(e){r.status(500).json({error:e.message})}});
app.listen(Number(process.env.PORT||3107),()=>console.log('Orders - Consignment ready'));
