'use strict';
const assert=require('node:assert/strict'),express=require('express'),fs=require('fs'),os=require('os'),path=require('path'),{spawn}=require('child_process');
const {coverage,age,validDay}=require('../modules/consignment/coverage');
assert.equal(validDay('2026-99-99'),false);assert.equal(age('2026-08-25',new Date('2026-09-30T12:00:00Z')).days,36);assert.equal(age('2026-08-24',new Date('2026-09-30T12:00:00Z')).bucket,'37–60 days old');assert.equal(age('2026-07-31',new Date('2026-09-30T12:00:00Z')).bucket,'61+ days old');assert.equal(age(null).days,null);
const intervals=[{start:'2026-09-01',end:'2026-09-15',status:'completed'},{start:'2026-09-16',end:'2026-09-30',status:'stopped'}];assert.equal(coverage(intervals)[0].complete,false);intervals[1].status='completed';assert.equal(coverage(intervals)[0].complete,true);
const listen=app=>new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s))});
async function main(){const reserve=await listen(express()),port=reserve.address().port;await new Promise(r=>reserve.close(r));const dir=fs.mkdtempSync(path.join(os.tmpdir(),'payout-test-'));function row(id,sale){return {id,sku:'GLEN-'+id,title:'Industrial Motor - '+id,order_number:'ORDER-'+id,quantity:1,date:'2026-07-15T15:00:00Z',currency:'USD',consigner:'Glen',amounts:{sale,buyer_shipping:0,selling_fees:0,shipping_cost:0,refund:0},payments:[],history:[],reviewed:true,shipping_kind:'actual',notes:'',weight:'12 lb',dimensions:null}}const rows=[row('one',20000),row('two',10000),row('legacy',20000)];rows[2].amounts.advertising_fees=1000;rows[2].payments.push({id:'old',amount:4000,reference:'Earlier payment',at:'2026-08-01'});fs.writeFileSync(path.join(dir,'consignment.json'),JSON.stringify({rows,scans:[{start:'2026-08-01',end:'2026-08-31',status:'completed'},{start:'2026-09-01',end:'2026-09-30',status:'running'}]}));const child=spawn(process.execPath,['server.js'],{cwd:path.join(__dirname,'../modules/consignment'),env:{...process.env,PORT:String(port),DATA_DIR:dir,SELLERCHAMP_TOKEN:''},stdio:['ignore','pipe','pipe']});const base=`http://127.0.0.1:${port}/api/`;async function api(url,body){const r=await fetch(base+url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,body:await r.json()}}
try{for(let i=0;i<100;i++){try{await api('status');break}catch{await new Promise(r=>setTimeout(r,20))}}let ledger=(await api('ledger')).body;assert.equal(ledger.scans[1].status,'interrupted');assert.equal(ledger.months.find(m=>m.month==='2026-08').complete,true);assert.equal(ledger.months.find(m=>m.month==='2026-09').complete,false);assert.equal(ledger.rows.find(r=>r.id==='legacy').totals.balance,5500,'Retain previous extra-fee deduction and payment');
const payload={request_key:'11111111-1111-4111-8111-111111111111',check_number:'1025',payment_date:'2026-09-30',notes:'Partial payment; retain balance for returns.',items:[{id:'one',amount:'50',expected_balance:10000},{id:'two',amount:'50',expected_balance:5000}]};let bad=JSON.parse(JSON.stringify(payload));bad.items[1].amount='100';assert.equal((await api('payouts',bad)).status,400);assert.equal((await api('ledger')).body.rows[0].payments.length,0,'Bulk validation must be atomic');bad=JSON.parse(JSON.stringify(payload));bad.items[1].expected_balance=5001;assert.equal((await api('payouts',bad)).status,400);bad=JSON.parse(JSON.stringify(payload));bad.payment_date='2026-02-31';assert.equal((await api('payouts',bad)).status,400);
const preview=await fetch(base+'payouts/preview-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});assert.equal(preview.status,200);assert.equal((await api('ledger')).body.rows[0].payments.length,0,'PDF preview must not record a payment');const result=await api('payouts',payload);assert.equal(result.status,201);assert.equal(result.body.payout.total,10000);const payout=result.body.payout;assert.equal((await api('payouts',payload)).status,200,'Identical retry is safe');bad=JSON.parse(JSON.stringify(payload));bad.items[0].amount='40';assert.equal((await api('payouts',bad)).status,409);ledger=(await api('ledger')).body;assert.equal(ledger.rows[0].totals.balance,5000);assert.equal(ledger.rows[1].totals.balance,0);assert.equal(ledger.rows[0].payments.length,1);const reused={...payload,request_key:'22222222-2222-4222-8222-222222222222',items:[{id:'one',amount:'10',expected_balance:5000}]};assert.equal((await api('payouts',reused)).status,409,'Duplicate check number must not pay again');assert.equal(ledger.rows[0].payments[0].check_number,'1025');assert.equal(ledger.rows[0].payments[0].payment_date,'2026-09-30');
await api('entry/one',{amounts:{sale:300},reviewed:true,shipping_kind:'actual'});const pdf=await fetch(base+'payouts/'+payout.id+'/pdf');assert.equal(pdf.status,200);const buf=Buffer.from(await pdf.arrayBuffer());assert.equal(buf.slice(0,4).toString(),'%PDF');fs.writeFileSync('/workspace/scratch/76339856353e/consignment-payout-test.pdf',buf);const snapshot=JSON.parse(fs.readFileSync(path.join(dir,'consignment.json'))).payouts[0];assert.equal(snapshot.items[0].share,10000);assert.equal(snapshot.items[0].remaining,5000);assert.equal(snapshot.items[0].amounts.sale,20000);assert.equal((await api('ledger')).body.rows[0].totals.balance,10000);console.log('Payout tests passed: month coverage, interrupted scans, ages, legacy fees, atomic partial check allocation, duplicate/stale protection, immutable PDF and payment history.');}finally{child.kill();fs.rmSync(dir,{recursive:true,force:true})}}main().catch(e=>{console.error(e);process.exitCode=1});
